name: First GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:

  hello:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Show Files
        run: ls -la

      - name: Display Message
        run: echo "Hello from GitHub Actions!"

      - name: Show Application
        run: cat index.html
